dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "lts/carbon"

branches:
  only:
    - master

script:
  - npm run build:all
  - npm run lint
  - npm test
  - npm run build:prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./dist/styleguide
  on:
    branch: master
