version: '3'
services:
    acpaas-ui:
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start:docker
        ports:
            - 4200:4200
        volumes:
            - .:/code
            - /code/node_modules